### ISSUE TITLE
@SqlBatch error: ! java.lang.IllegalArgumentException: argument must be one of the following: Iterable, or an array/varargs (primitive or complex type); was java.util.UUID instead

### ISSUE THREAD

**Issue by sulmansarwar** [jdbi/jdbi#1202] opened 2018-07-26 06:30 UTC
Here are my DAO methods:

```
@SqlUpdate("INSERT INTO <schema>.syllabus (syllabus_name,syllabus_description) "
      + " values ('<syllabus_name>', '<syllabus_description>')")
  @UseStringTemplateEngine
  @RegisterBeanMapper(Syllabus.class)
  @GetGeneratedKeys
  Syllabus insertSyllabus(@Define("schema") String schema, @Define("syllabus_name") String syllabusName,
      @Define("syllabus_description") String syllabusDescription);

```

```
  @SqlBatch("INSERT INTO <schema>.syllabus_lessons (syllabus_id,lesson_id) "
      + " values (<syllabus_id>, :lessons)")
  @UseStringTemplateEngine
  void insertSyllabusLessons(@Define("schema")String schema,
      @Define("syllabus_id")String syllabusId, @BindList("lessons")List<UUID> lessons);

```

```
  @Transaction
  default Syllabus insert(String schema, String syllabusName,
      String syllabusDescription, List lessons){

    Syllabus syllabus = insertSyllabus(schema, syllabusName, syllabusDescription);
    if(!lessons.isEmpty()) {
      insertSyllabusLessons(schema, syllabus.getSyllabusId(),lessons);

    }
    Syllabus newSyllabus = selectOne(schema,syllabus.getSyllabusId());

    return newSyllabus;
  }
```

And I get following exception when i run this. What am i missing?

```
! java.lang.IllegalArgumentException: argument must be one of the following: Iterable, or an array/varargs (primitive or complex type); was java.util.UUID instead
! at org.jdbi.v3.core.internal.IterableLike.isEmpty(IterableLike.java:93)
! at org.jdbi.v3.sqlobject.customizer.internal.BindListFactory.lambda$createForParameter$1(BindListFactory.java:44)
! at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.lambda$null$6(CustomizingStatementHandler.java:99)
! at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.lambda$applyCustomizers$9(CustomizingStatementHandler.java:161)
! at java.util.ArrayList.forEach(ArrayList.java:1249)
! at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.applyCustomizers(CustomizingStatementHandler.java:159)
! at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler$2.hasNext(SqlBatchHandler.java:205)
! at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler$2.<init>(SqlBatchHandler.java:182)
! at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.invoke(SqlBatchHandler.java:179)
! at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:158)
! at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:27)
! at org.jdbi.v3.core.LazyHandleSupplier.lambda$invokeInContext$1(LazyHandleSupplier.java:68)
! at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:27)
! at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:67)
! at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:157)
! at com.sun.proxy.$Proxy65.insertSyllabusLessons(Unknown Source)
! at au.edu.unimelb.sqn725.db.SyllabusDAO.insert(SyllabusDAO.java:68)
! at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
! at org.jdbi.v3.sqlobject.DefaultMethodHandler.invoke(DefaultMethodHandler.java:101)
! at org.jdbi.v3.sqlobject.transaction.internal.TransactionDecorator.lambda$null$0(TransactionDecorator.java:50)
! at org.jdbi.v3.core.transaction.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:132)
! at org.jdbi.v3.core.Handle.inTransaction(Handle.java:379)
! at org.jdbi.v3.sqlobject.transaction.internal.TransactionDecorator.lambda$decorateHandler$1(TransactionDecorator.java:59)
! at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:158)
! at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:27)
! at org.jdbi.v3.core.LazyHandleSupplier.lambda$invokeInContext$1(LazyHandleSupplier.java:68)
! at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:27)
! at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:67)
! at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:157)
! at org.jdbi.v3.core.OnDemandExtensions.invoke(OnDemandExtensions.java:75)
! at org.jdbi.v3.core.OnDemandExtensions.lambda$null$0(OnDemandExtensions.java:63)
! at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:27)
! at org.jdbi.v3.core.OnDemandExtensions.lambda$null$1(OnDemandExtensions.java:62)
! at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:438)
! at org.jdbi.v3.core.OnDemandExtensions.lambda$create$2(OnDemandExtensions.java:61)
! at com.sun.proxy.$Proxy65.insert(Unknown Source)
! at au.edu.unimelb.sqn725.services.SyllabusService.addNewSyllabus(SyllabusService.java:39)
! at au.edu.unimelb.sqn725.resources.SyllabusResource.createSyllabus(SyllabusResource.java:69)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
! at io.dropwizard.jetty.ContextRoutingHandler.handle(ContextRoutingHandler.java:38)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:674)
! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at org.eclipse.jetty.server.Server.handle(Server.java:531)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
! at java.lang.Thread.run(Thread.java:745)
```

**Comment by TheRealMarnes** [comment] 2018-07-26 07:06
Your query uses string templating to bind query variables. You shouldn't do that — do you have a good reason for it like a db that doesn't support query params?

```
@SqlUpdate("INSERT INTO <schema>.syllabus (syllabus_name,syllabus_description) values (:syllabus_name, :syllabus_description)")
@UseStringTemplateEngine
@RegisterBeanMapper(Syllabus.class)
@GetGeneratedKeys
Syllabus insertSyllabus(@Define("schema") String schema, @Bind("syllabus_name") String syllabusName, @Bind("syllabus_description") String syllabusDescription);
```

```
@SqlBatch("INSERT INTO <schema>.syllabus_lessons (syllabus_id,lesson_id) values (:syllabus_id, :lessons)")
@UseStringTemplateEngine
void insertSyllabusLessons(@Define("schema") String schema, @Bind("syllabus_id") String syllabusId, @BindList("lessons") List<UUID> lessons);
```

That aside, I don't see any obvious mistake here. Unless I'm overlooking something, it looks correct usage-wise. I wrote the code that triggers this exception so I'll try to take a look tonight if I can reproduce and fix it.

**Comment by sulmansarwar** [comment] 2018-07-27 21:59
@TheRealMarnes Thanks for taking a look. I am using string template to provide value for <schema> parameter. @Bind does not bind values to this part of the query. I have tried what you suggested above but no success. I still get the same error. Did  you find anything or were able to reproduce?

**Comment by TheRealMarnes** [comment] 2018-07-28 11:53
```
public interface DAO {
	@SqlUpdate("INSERT INTO <schema>.syllabus (syllabus_name,syllabus_description) values ('<syllabus_name>', '<syllabus_description>')")
	@UseStringTemplateEngine
	@RegisterBeanMapper(Syllabus.class)
	@GetGeneratedKeys
	Syllabus insertSyllabus(@Define("schema") String schema, @Define("syllabus_name") String syllabusName, @Define("syllabus_description") String syllabusDescription);

	@SqlBatch("INSERT INTO <schema>.syllabus_lessons (syllabus_id,lesson_id) values (<syllabus_id>, :lessons)")
	@UseStringTemplateEngine
	void insertSyllabusLessons(@Define("schema") String schema, @Define("syllabus_id") String syllabusId, @BindList("lessons") List<UUID> lessons);

	@SqlQuery("select * from <schema>.syllabus where syllabus_id = :id")
	Syllabus selectOne(@Define("schema") String schema, @Bind("id") String id);

	@Transaction
	default Syllabus insert(String schema, String syllabusName, String syllabusDescription, List<UUID> lessons) {
		Syllabus syllabus = insertSyllabus(schema, syllabusName, syllabusDescription);
		if (!lessons.isEmpty()) {
			insertSyllabusLessons(schema, syllabus.getSyllabusId(), lessons);

		}
		return selectOne(schema, syllabus.getSyllabusId());
	}
}
```

`jdbi.useExtension(DAO.class, dao -> dao.insert(SCHEMA, "name", "desc", Collections.emptyList()));`

> Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: SYLLABUS

jdbi 3.3.0 isn't giving me any trouble with this code. Are you sure the code you gave there matches your source?

**Comment by TheRealMarnes** [comment] 2018-07-28 12:07
Could you provide full demo code please? Just zip up a project where I can reproduce it. I'm trying to recreate what you have but I need to find a database that supports getGeneratedKeys, set up your tables, etc.

**Comment by TheRealMarnes** [comment] 2018-07-30 11:37
Ok, so, I took the liberty of reducing your case to the essentials:

```
@Inject
private DataSource dataSource;

@Test
public void test() {
	Jdbi jdbi = Jdbi.create(dataSource).installPlugin(new SqlObjectPlugin());

	jdbi.useHandle(h -> h.createUpdate("create schema sch").execute());
	jdbi.useHandle(h -> h.createUpdate("create table sch.syllabus_lessons (syllabus_id longvarchar, lesson_id uuid)").execute());

	jdbi.useExtension(DAO.class, dao -> dao.insertSyllabusLessons("sch", "syll", Arrays.asList(UUID.randomUUID(), UUID.randomUUID())));

	List<Map<String, Object>> result = jdbi.withHandle(h -> h.createQuery("select * from sch.syllabus_lessons").mapToMap().list());
	assertThat(result).hasSize(2);
	System.out.println(result);
}

public interface DAO {
	@SqlBatch("INSERT INTO <schema>.syllabus_lessons (syllabus_id,lesson_id) values ('<syllabus_id>', :lessons)")
	@UseStringTemplateEngine
	void insertSyllabusLessons(@Define("schema")String schema, @Define("syllabus_id") String syllabusId, @BindList("lessons") List<UUID> lessons);
}
```

This gives the exception you mentioned.

> java.lang.IllegalArgumentException: argument must be one of the following: Iterable, or an array/varargs (primitive or complex type); was java.util.UUID instead

The key is to change the `BindList` to simply `Bind`:

```
public interface DAO {
	@SqlBatch("INSERT INTO <schema>.syllabus_lessons (syllabus_id,lesson_id) values ('<syllabus_id>', :lessons)")
	@UseStringTemplateEngine
	void insertSyllabusLessons(@Define("schema")String schema, @Define("syllabus_id") String syllabusId, @Bind("lessons") List<UUID> lessons);
}
```

> [{syllabus_id=syll, lesson_id=94b2fa57-6038-41b3-99d0-c08cb6d8f6e7}, {syllabus_id=syll, lesson_id=85841674-0e15-48b5-a834-eb0ab7e75b09}]

This sounds contradicting but it's actually logical because you're using batching. In batch mode, iterable arguments will be iterated and passed to the sqlobject method as individual objects. This means that your `lessons` param won't be a list of UUIDs but a single UUID (for each repeated invocation) and thus needs `Bind`.

I tried going the other way and using `BindList` to bind a `List<List<UUID>>`, which I'd expect batching to iterate so that a `List<UUID>` would be inserted into each record:

```
@Test
public void test() {
	Jdbi jdbi = Jdbi.create(dataSource).installPlugin(new SqlObjectPlugin());

	jdbi.useHandle(h -> h.createUpdate("create schema sch").execute());
	jdbi.useHandle(h -> h.createUpdate("create table sch.syllabus_lessons (syllabus_id longvarchar, lesson_id blob)").execute());

	jdbi.useExtension(DAO.class, dao -> dao.insertSyllabusLessons("sch", "syll", Arrays.asList(singletonList(UUID.randomUUID()), singletonList(UUID.randomUUID()))));

	List<Map<String, Object>> result = jdbi.withHandle(h -> h.createQuery("select * from sch.syllabus_lessons").mapToMap().list());
	assertThat(result).hasSize(2);
	System.out.println(result);
}

public interface DAO {
	@SqlBatch("INSERT INTO <schema>.syllabus_lessons (syllabus_id,lesson_id) values ('<syllabus_id>', :lessons)")
	@UseStringTemplateEngine
	void insertSyllabusLessons(@Define("schema")String schema, @Define("syllabus_id") String syllabusId, @BindList("lessons") List<List<UUID>> lessons);
}
```

However this fails with an exception:

> org.jdbi.v3.core.statement.UnableToExecuteStatementException: Unable to execute, no named parameter matches 'lessons'. [statement:"INSERT INTO <schema>.syllabus_lessons (syllabus_id,lesson_id) values ('<syllabus_id>', :lessons)", rewritten:"INSERT INTO sch.syllabus_lessons (syllabus_id,lesson_id) values ('syll', :lessons)", parsed:"ParsedSql{sql='INSERT INTO sch.syllabus_lessons (syllabus_id,lesson_id) values ('syll', ?)', parameters=ParsedParameters{positional=false, parameterNames=[lessons]}}", arguments:{ positional:{}, named:{__lessons_0:cfbccaf5-8c50-462e-93cd-51e042796823}, finder:[]}]

@qualidafial @stevenschlansker This smells like an actual problem to me, but is separate from @sulmansarwar 's case. I've never used jdbi batching though so I may be wrong. The dev guide mentions

```
@SqlBatch("INSERT INTO fruit VALUES(:id, :name)")
int[] fillBasket(@BindBean Collection<Fruit> fruits);
```

so maybe this is just a problem specifically with `BindList`? Or am I doing something wrong?

**Comment by stevenschlansker** [comment] 2018-07-30 16:45
Correct, you need to use `@Bind` not `@BindList` -- `@BindList` is used to template the list elements *into the sql* as opposed to a proper parameter.

This is in fact the same reason you can't prepare a batch with a `@BindList` -- prepared batches execute the same statement repeatedly with different bindings.  If you vary the statement and not the bindings, you cannot sensibly prepare a batch.

(There is the simpler Batch instead of PreparedBatch -- but that's different yet again)

Please feel to continue discussion, but closing as answered.

**Closed by stevenschlansker** 2018-07-30 16:45 UTC

**Comment by TheRealMarnes** [comment] 2018-07-30 16:52
One thing that does not really compute to me is that you mention different statements as if binding a different list creates a different statement. I suppose this is because we don't _really bind_ lists but rather render them and they only appear as a high-level binding to the user?

I'm thinking we should maybe create a validator of some sort in SqlObject, something that checks for illegal combinations of parameters and warns users at construction time that e.g. `SqlBatch` and `BindList` can never be combined.

**Comment by stevenschlansker** [comment] 2018-07-30 18:07
Right, @BindList changes the SQL, which does not mix with `PreparedBatch`.
Better error messaging here would be quite welcome.  I don't know that a central validator approach will be better than simply catching errors in the sqlobject code at point of use, which would be my natural first pass.

**Comment by TheRealMarnes** [comment] 2018-07-30 18:24
We can detect it _will_ fail that early, so it would be good to warn that early.

> you cannot use BindList with batch statements

is also a lot more informative than

> could not find named parameter __foo_0

**Comment by qualidafial** [comment] 2018-08-06 21:44
I believe `@BindList` would be valid on a batch, if used in conjunction with `@SingleValue`.

**Comment by nixos89** [comment] 2019-11-23 16:16
> I believe `@BindList` would be valid on a batch, if used in conjunction with `@SingleValue`.

Unfortunately that wont' work in DW 1.3.8 (I've tested it).

**Comment by qualidafial** [comment] 2019-11-25 21:23
I've read through the thread more carefully this time. The others are right--you should be using `@Bind` on your `List<UUID>` parameter instead of `@BindList` in this case.

`@BindList` is most commonly used for queries like `SELECT * FROM foo WHERE id IN (<ids>)`. The `<ids>` template parameter is expanded inline into the SQL as `..WHERE id in (:__ids_0, :__ids_1, :__ids_2, ... :__ids_n)`.

However you are using `@SqlBatch`, which already has special handling for iterable or array parameters, and unrolls them into the batch for you.
