### ISSUE TITLE
`UseClasspathSqlLocatorImpl` should throw an error on failure

### ISSUE THREAD

**Issue by toadzky** [jdbi/jdbi#1388] opened 2019-01-01 20:50 UTC
The `UseClasspathSqlLocatorImpl` just returns the name of the expected file when it fails to load. This means the parser is given `methodName.sql` as the "located sql" to parse. If the resource can't be found or loaded, that error should be propagated, not swallowed.

**Comment by TheRealMarnes** [comment] 2019-01-01 22:02
@stevenschlansker was this a deliberate design decision? It's very explicit in the code, but could also just have been used as a gap filler at the time.

**Comment by qualidafial** [comment] 2019-01-02 17:59
I think this is a vestige of the the way things worked in v2, that we failed to remove in v3. I'm calling this a bug.

In v2, loading SQL from the classpath was automatic if the string didn't "look like" SQL. We then assumed it was a filename, and replaced it with the file contents if found on the classpath. Otherwise we fell back to the string in case our "looks like SQL" check was flawed.

In v3 we made the decision to stop doing that, that whatever gets handed to the SQL statement must be SQL, and that any SQL loading from the classpath should happen before the statement was created. The fact this behavior is still there is an omission.

**Comment by TheRealMarnes** [comment] 2019-01-02 18:52
Sounds right to me. Just do or don't do > heuristics

**Comment by TheRealMarnes** [comment] 2019-01-27 18:31
@toadzky I can only reproduce the name of the method being returned as if it were an sql query when a file matching the annotation exists but is empty. Is that the case this is about or am I missing something?

**Comment by TheRealMarnes** [comment] 2019-01-27 18:35
See the commit I just pushed for the test case as I see it atm, which should fail when this is fixed

**Comment by TheRealMarnes** [comment] 2019-01-27 18:45
I also just pushed the fix and adapted the test for it, please check if this is what you intended so I can make a PR of it.

**Comment by toadzky** [comment] 2019-01-28 16:02
yes, the situation i had was the file was in the wrong folder so it wasn't being found. fix looks good to me :+1:

**Closed** 2019-01-30 00:59 UTC
Labels: bug
