### ISSUE TITLE
Does JDBI support: IBM DB2, Oracle DB, and EhCache?

### ISSUE THREAD

**Issue by gencube** [jdbi/jdbi#808] opened 2017-05-03 05:20 UTC
I really like the Fluent pattern in JDBI, I dislike the Spring's JdbcTemplate. 
I wish to introduce this to my development team.
**However,** to use this to replace the really old code pattern we have in my company, 
I need to ensure JDBI or what ever fluent API someone can suggest to support:
IBM DB2(Production DB), Oracle DB(Development DB) and also some form of
Caching like within Hibernate DAO using EhCache.

**Thanks a lot in advance!!!**

**Comment by qualidafial** [comment] 2017-05-03 05:56
It depends on whether you're looking to target v2 or v3 (still in beta).

Jdbi uses JDBC, so as long as you have a good JDBC driver for your database vendor, you should be good.

In v3 we are making an effort to provide plugins for the various databases out there. Postgres is our best-selling db. We also have a very minimal Oracle plugin. Nothing for DB2 yet.

Jdbi does not have caching, by design. However we do provide some hooks in v3 to make it possible to wire up your own caching in a SQL Object, using "SQL decorating annotations." If you're interested in pursuing this, I can point you in the right direction.

**Comment by qualidafial** [comment] 2017-05-03 05:58
Ugh, autocorrect. Meant to say:

> Postgres is our best-supported db.

**Comment by gencube** [comment] 2017-05-03 11:37
In v3 we are making an effort to provide plugins for the various databases out there. Postgres is our best-supported db. We also have a very minimal Oracle plugin. Nothing for DB2 yet. <<< ....SAD.
-------
Jdbi does not have caching, by design. However we do provide some hooks in v3 to make it possible to wire up your own caching in a SQL Object, using "SQL decorating annotations." If you're interested in pursuing this, I can point you in the right direction. <<< :D Good good. Have this Quick!!!

**Comment by qualidafial** [comment] 2017-05-03 13:38
Keep in mind: most common data types (primitives, dates / times, Strings,
etc) are supported out of the box. Plugins for specific database vendors
only add support for unqie features of a specific JDBC driver--e.g. the
Postgres driver supports intervals, so we provide arguments and mappers
that map those to e.g. java.time.Duration.

**Comment by qualidafial** [comment] 2017-05-04 01:38
Here's some broad ideas for adding caching support.

Introduce a config class to hold the `CacheManager`:

```java
public class EhCacheConfig implements JdbiConfig<EhCacheConfig> {
  ...
  public void setCacheManager(CacheManager cacheManager) { ... }
  public Cache getCache(String name) { ... }
}
```

Inject the cache into your config class, while you set up `Jdbi`:

```java
CacheManager cacheManager = ...
Jdbi jdbi = ...
jdbi.getConfig(EhCacheConfig.class).setCacheManager(cacheManager);
```

Introduce a SQL method decorating annotation:

```java
@SqlMethodDecoratingAnnotation(CachedDecorator.class)
public @interface Cached {
  String value(); // cache name
}
```

Implement the `HandlerDecorator` to attach caching behavior to that annotation:

```java
public class CachedDecorator implements HandlerDecorator {
  Handler decoratorHandler(Handler base, Class<?> sqlObjectType, Method method) {
    String cacheName = method.getAnnotation(Cached.class).value();

    return (target, args, handle) -> {
      Cache cache = handle.getConfig(EhCacheConfig.class).getCache(cacheName);

      // munge the arguments into a cache key, somehow. Maybe a @CacheKey annotation?
      String key = ...

      Object value = cache.get(key);
      if (value == null) {
        value = base.invoke(target, args, handle);
        cache.put(key, value);
      }
      return value;
    };
  }
}

```

References:

* [Handler interface](http://jdbi.github.io/apidocs/org/jdbi/v3/sqlobject/Handler.html) - The basic plumbing of SQL Objects. When Jdbi synthesizes an implementation of your interfaces, this resolves to a `Handle` per interface method. When your SQL object method is invoked, it delegates to the `Handle` for that method.
* [HandlerDecorator interface](http://jdbi.github.io/apidocs/org/jdbi/v3/sqlobject/HandlerDecorator.html) - Decorates (wraps) a `Handler` in another `Handler`, which may add or modify the behavior of the original. In the case of caching: a cache hit may simply return the cached value without calling the delegate handle. A cache miss should call into the wrapped `Handler`, cache the result, and then return it.
* [@SqlMethodDecoratingAnnotation meta-annotation](http://jdbi.github.io/apidocs/org/jdbi/v3/sqlobject/SqlMethodDecoratingAnnotation.html) - Invent your own SQL Object annotations, and attach behavior to them. Annotate your annotation type:
* [HandlerDecorators config class](http://jdbi.github.io/apidocs/org/jdbi/v3/sqlobject/HandlerDecorators.html) - An alternative approach to meta-annotations. Decorators registered on this config class are consulted for _every_ method of a SQL object, and may optionally decorate any of them on whatever basis you like.
* [Unit tests that give some basic examples of how to implement a decorator](https://github.com/jdbi/jdbi/blob/master/sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestSqlMethodDecorators.java)
* Look at the [@Transaction annotation](https://github.com/jdbi/jdbi/blob/master/sqlobject/src/main/java/org/jdbi/v3/sqlobject/transaction/Transaction.java) for a non-toy example.

**Comment by qualidafial** [comment] 2017-05-04 01:47
Closing this question as answered. Feel free to ask follow up questions if you like.

If you want to see some movement on DB2 support, please open a separate issue, and list the specific DB2-specific features you'd like to see supported.

**Closed by qualidafial** 2017-05-04 01:47 UTC
Labels: question

**Comment by gencube** [comment] 2017-05-04 02:07
I am on GMT+0800 now is 10am. Thanks for the answer. REALLY appreciate it. I like to see your JDBI pattern a success and less complex to develop than Hibernate/JdbcTemplate(Spring)...
