### ISSUE TITLE
Evaluate SQLObject implementation choices

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#341] opened 2016-05-02 23:22 UTC
Currently, we use `cglib` to generate implementation classes.
There's an open question to changing this approach, either
* JDK standard dynamic Proxy instances
* Compile time annotation processor that generates code

**Comment by qualidafial** [comment] 2016-05-02 23:45
Important to consider: with `java.lang.reflect.Proxy` we are restricted to interfaces only--no classes. With Java 8's default interface methods, it's probably no big deal.

But whichever route we take, let's not expose any implementation details. That way we can pivot in the future, should a better alternative emerge.

**Comment by qualidafial** [comment] 2016-08-21 05:30
My vote on this would be to use proxies for the time being. If the interface-only limitation turns out to be a problem, we can always migrate to something else.

**Comment by umcodemonkey** [comment] 2016-08-24 21:39
Being limited to interfaces only is a *huge* deal. We use abstract classes all the time in our SQL object implementations. Default interface methods are not a substitute.

I would also be surprised if the Proxy implementation had similar performance to CGLIB generated code. I would hope to see considerable perf testing on any replacement solution to ensure there isn't any regression on what can be a very perf sensitive part of an application.

Annotation processing could possibly work, but it has its own downsides of potentially depending on the concrete implementation that's generated, and also the additional tooling that is needed to support them.

I'm really surprised this is even an issue. Is there some huge drawback to the CGLIB code (other than debugger tracing, which I'll admit can be challenging) that you hope to address by making a change?

**Comment by qualidafial** [comment] 2016-08-24 22:44
@umcodemonkey Could you provide examples of sql objects that would not work as an interface?

**Comment by umcodemonkey** [comment] 2016-08-26 21:29
In many cases it's needed to migrate legacy non-JDBI database classes to JDBI incrementally, without having to do a whole rewrite. In other cases we need to support state in the DAO, either for metrics collection or other in-app bookkeeping. In these two cases, composition could achieve similar goals (having the JDBI generated class be a member of the legacy or stateful class), but that does introduce maintenance overhead in many cases.

I'm still curious to hear what's driving the motivation to replace CGLIB. If there's an email thread someone can point me to, I'd appreciate it.

**Comment by qualidafial** [comment] 2016-08-30 17:48
This issue is about exploring alternatives to CGLIB to see if there's a better option.

We're simply taking this opportunity (pre-v3 release) to evaluate alternatives and see if other approaches might serve us better.

A few soft motivations I have are:

* Minimize external dependencies
* Minimize JDBI's total footprint (including dependencies)
* Simplify the project code.
* Simplify usage.

I personally see the interface-only restriction as a simplification, both from a project maintenance standpoint, and from a usage standpoint.

And if I'm totally honest, I like it _because_ it prevents folks from trying to keep state in their DAOs, which I view as an antipattern. We've taken great pains to make SQL objects thread safe, and keeping state in fields undermines this.

Speaking of composition, we just opened up some of the SQL Object plumbing (`@SqlMethodAnnotation` and `@SqlMethodDecoratingAnnotation`) as supported API. We're hopeful that these will be a good way to achieve metrics collections and other bookkeeping, so please kick the tires and give us your feedback.

**Comment by qualidafial** [comment] 2016-08-31 02:48
Just a small follow up, since I feel my earlier comment may have come across a bit harsh.

First, we haven't reached a firm decision on any of this. I have my reasons for preferring the Java proxy solution, but I'm just one member of the team.

Second, I'm sympathetic to the difficulty of migrating to JDBI. I'm in the midst of a Hibernate-to-JDBI migration myself at the moment. So I'm not dismissing your concerns--rather, I'm hopeful that we can come up with a different approach that permits a gradual migration while avoiding the pitfalls of keeping state in DAOs.

**Comment by arteam** [comment] 2016-08-31 17:36
I like the idea of moving from CGLib to the Java proxy implementation. 

* Default methods in Java 8 provide the same functionality as stateless methods in abstract classes in previous Java versions. So, CGLib is not _required_ now to provide this feature.
* This move will underline fact that the JDBI maintainers consider state in DAOs (caches, counters, etc...) as a bad practice, which should be performed on the service level.
* Less dependencies - less points of failure. Bytecode manipulation is a rather fragile technique. For example, I experienced problems to migrate several applications to Java 8, because they needed the latest version of CGLib. I don't know if the current version of CGLib works correctly with JDK9, but I think the proxy approach should be more portable, because it uses only the public JDK API.

The downside is that the proxy approach may be slower than the CGLib approach, because it requires a virtual method dispatch and additional stack frame to make a call. A JVM may decide not to inline such calls, whereas GCLib generates plain byte code which could be easily inlined. I believe the difference should not be more than 10 nanoseconds (hard to say without a _proper_ benchmark).
Another issue pointed out by @umcodemonkey is that users will have to move their applications from abstract classes to interfaces with default methods. This should be a rather easy migration for users who use stateless abstract classes, but could be a blocking issue for those who actually put a state in their DAO and want to upgrade to JDBI3.

**Comment by qualidafial** [comment] 2016-08-31 19:21
I don't think CGLIB is helping us much in terms of performance, honestly. We're not really taking advantage of CGLIB at the moment--rather, we're using MethodInterceptor exactly how Proxy uses InvocationHandler. The approaches are effectively identical, the way we're using it.

**Comment by qualidafial** [comment] 2016-09-30 05:57
@stevenschlansker with #456 merged, can we close this issue?

**Closed** 2016-09-30 19:33 UTC
Labels: cleanup
