### ISSUE TITLE
SQLBatch issues in generic class

### ISSUE THREAD

**Issue by PreXident** [jdbi/jdbi#1473] opened 2019-02-22 08:58 UTC
Hello, I just encountered a problem with SQLBatch inside a generic class.
```
@UseClasspathSqlLocator
public interface BaseDAO<T> {
    @SqlBatch
    void insertAll(@BindBean("e") Collection<T> entities);
}

public interface AirspaceDAO extends BaseDAO<Airspace> {

}
```

When trying to get jdbi implementation of the AirspaceDAO via handle.attach, I get this exception:
```
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.getParameterType(SqlBatchHandler.java:158)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.lambda$eachParameterCustomizers$5(CustomizingStatementHandler.java:98)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.eachParameterCustomizers(CustomizingStatementHandler.java:99)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.lambda$parameterCustomizers$4(CustomizingStatementHandler.java:89)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.<init>(CustomizingStatementHandler.java:73)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.<init>(SqlBatchHandler.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jdbi.v3.sqlobject.SqlMethodHandlerFactory.buildHandler(SqlMethodHandlerFactory.java:68)
	at org.jdbi.v3.sqlobject.SqlMethodHandlerFactory.lambda$buildHandler$2(SqlMethodHandlerFactory.java:57)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.jdbi.v3.sqlobject.SqlMethodHandlerFactory.buildHandler(SqlMethodHandlerFactory.java:58)
	at org.jdbi.v3.sqlobject.Handlers.lambda$findFor$0(Handlers.java:56)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.jdbi.v3.sqlobject.Handlers.findFor(Handlers.java:57)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.buildMethodHandler(SqlObjectFactory.java:133)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$9(SqlObjectFactory.java:125)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$methodHandlersFor$10(SqlObjectFactory.java:125)
	at java.util.Map.computeIfAbsent(Map.java:957)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.methodHandlersFor(SqlObjectFactory.java:106)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.attach(SqlObjectFactory.java:83)
	at org.jdbi.v3.core.extension.Extensions.lambda$findFor$0(Extensions.java:70)
	at java.util.Optional.map(Optional.java:215)
	at org.jdbi.v3.core.extension.Extensions.findFor(Extensions.java:70)
	at org.jdbi.v3.core.Handle.attach(Handle.java:504)
```
However when I override the method in the descendant, it works fine.
```
public interface AirspaceDAO extends BaseDAO<Airspace> {

    @SqlBatch
    @Override
    void insertAll(@BindBean("e") Collection<Airspace> entities);
}
```
When debugging I looked into GenericTypes.findGenericParameter, and in problematic case parameterType is instance of TypeVariableImpl, but I do not know if it is helpful.
```
    public static Optional<Type> findGenericParameter(Type type, Class<?> parameterizedSupertype) {
        Type parameterType = resolveType(parameterizedSupertype.getTypeParameters()[0], type);
        return parameterType instanceof Class || parameterType instanceof ParameterizedType
                ? Optional.of(parameterType)
                : Optional.empty();
    }
```
Is this use case not supported or am I using a wrong approach? Thanks a lot for answer!

**Comment by TheRealMarnes** [comment] 2019-02-22 09:04
My first impression is it ought to work because you've created a class that concretely types the `T`. We'll probably wanna check this out.

**Comment by TheRealMarnes** [comment] 2019-02-22 09:37
My next thought is this looks like it's because the method being used is the `T` typed one from the interface, not the "virtual" concretely typed inherited method. Whether that's expected behavior or a bug is above my books atm.

**Comment by qualidafial** [comment] 2019-02-22 23:16
Sounds like we're not resolving the parameter T in the context of the DAO interface. We're doing that in other places like `@SqlQuery` though so the fix shouldn't be hard.

**Comment by qualidafial** [comment] 2019-02-22 23:35
I have a unit test that captures the error, and a fix. PR incoming..

**Comment by PreXident** [comment] 2019-02-23 10:35
Great to hear! Thanks for the quick fix. I will try it on Monday :-)

**Closed** 2019-02-23 18:01 UTC
Labels: bug
