### ISSUE TITLE
Support for jdbi calling mainframe stored procedure with OUT param and returning multiple resultset.

### ISSUE THREAD

**Issue by rpawarmca** [jdbi/jdbi#451] opened 2016-08-18 22:38 UTC
looks like jdbi is not supporting calling mainframe stored procedure with multiple out parameter and returning multiple result set.

**Comment by rpawarmca** [comment] 2016-08-22 22:27
@stevenschlansker Hi Steve, Are we considering this feature in JDBI?

**Comment by stevenschlansker** [comment] 2016-08-23 17:12
Hi @rpawarmca yes, we would consider this use case for jdbi.  However to be perfectly honest this is a very edge case that we did not consider.  jdbi often assumes that you only return a single result type, either a `ResultSet`-like object or an `OutParameters` -- but has no facility for returning both.  So I think this is not a trivially added feature.

If you need it urgently, I would encourage you to prototype it yourself -- the core developers are busy working on more widely used features, and may not get to this one imminently.  Also keep in mind that you can continue to use jdbi for the majority of your database code but for this single situation get a standard JDBC `Connection` via `Handle.getConnection().  Then you can `prepareCall` yourself.  This might be the most expedient solution for your situation.

**Comment by rpawarmca** [comment] 2016-08-23 18:17
Thanks Steve, Yes for time being we are using jdbi to open connection and going old way of callable statement.

**Comment by stevenschlansker** [comment] 2016-11-27 02:57
This looks like it's mostly a duplicate of #76

**Closed by stevenschlansker** 2016-11-27 02:57 UTC
