### ISSUE TITLE
Poor DAO performance in jdbi3

### ISSUE THREAD

**Issue by gtaborcrossword** [jdbi/jdbi#1732] opened 2020-07-16 08:04 UTC
Because I spotted the degraded performance of SqlObject (DAO) calls between jdbi2 and jdbi3, I did some quick and simple comparison tests.

The test code itself is very simple - it is just two database operations in the loop. The first operation inserts the record into the database, second operation just reads it using the primary key.

**Test conditions**
- jdbi3 - v3.13.0
- jdbi2 - v2.78
- database: local Postgresql 11.7
- JDBC driver - postgresql:42.2.12

**Results**

1. Execution time in milliseconds, `num` is a number of iterations.
```
  num     3-DAO    2-DAO    3-API    2-API
   10       480      165      167      159
  100     3 769      690      690      643
 1000    31 259    4 771    4 800    4 889
10000   291 862   39 221   40 308   42 069
```

2. Iteration average execution time in milliseconds.
```
  num   3-DAO   2-DAO   3-API   2-API
   10   48.00   16.50   16.70   15.90
  100   37.69    6.90    6.90    6.43
 1000   31.25    4.77    4.80    4.88
10000   29.18    3.92    4.03    4.20
```

**Conclusions/Comments**

 * The difference between "3-DAO" column and the others is obvious and significant. I'm conscious of switch from cglib to dynamic proxies between jdbi2 and jdbi3 (#341, #456), but that level of degradation is really worrying.
 * I didn't notice any other symptoms that could justify such difference - no connection leakage, no increasing memory consumption.
 
Any ideas what could be wrong? Maybe some other cglib alternative could be considered/verified (e.g Byte Buddy)?

**Comment by stevenschlansker** [comment] 2020-07-16 14:02
Thanks for measuring this @gtaborcrossword .  Could you please share your benchmarks, preferably as run by JMH?  I would like to try to reproduce your results.  Usually we find that the overhead of Proxy objects is very low compared to the cost of a remote call to the database, but of course we would always love to find improvements :)

**Comment by stevenschlansker** [comment] 2020-07-16 14:09
Also, you could try using the new `jdbi3-generator` code generator artifact to replace the Proxy based implementation with a generated source file.  That should highlight the possibility of Proxy being the root cause or not.

**Comment by gtaborcrossword** [comment] 2020-07-20 08:34
Thanks @stevenschlansker. I'll surely will do both.

**Comment by natan-abolafya** [comment] 2020-08-13 15:03
Hi, a dropwizard user here.

We have noticed a performance degradation of around 10-15% after updating our dropwizard 2.0.6 (jdbi 3.12.2) to 2.0.9 (jdbi 3.13.0). Also tried 2.0.12 (jdbi 3.14.1) but that has not helped. I tried bumping jdbi to 3.14.1 on dropwizard 2.0.6 and the performance degradation was there, ruling out a problem with dropwizard.

Our application involves a lot of different way of using jdbi, so I can't pinpoint any feature or anything. But I hope the versions are helpful.

**Comment by stevenschlansker** [comment] 2020-08-13 15:23
Hi Natan, thanks for the additional information.  Do you happen to have a profiler handy and could take some basic performance measurements to share?  Or perhaps prepare a self contained runnable case for us to look at?  It is hard to see how a complex authentication system would bottleneck so seriously on Jdbi, especially on such a small patch change, so having some data would be very helpful!


You're right, 3.14.2 release was messed up.  I'm confused because I still see this history in my terminal where I performed it, seemingly correctly...  Regardless, fixing it now.

**Comment by natan-abolafya** [comment] 2020-08-13 16:07
Unfortunately I'm really bad with profiling. I tried to play with VisualVM but all I get is unreliable results. When I profile for `org.jdbi.**` things get incredibly slow and unreliable. I also couldn't yet figure out how to export stuff from VisualVM.

But in case it's still helpful, here are some results from my profiling attempts on my local workstation in a limited time:
3.12.2
![image](https://user-images.githubusercontent.com/64091305/90158620-83d41e80-dd8f-11ea-981a-4269c76539a6.png)

3.14.1 (for some reason reported slower, probably due to the profiling)
![image](https://user-images.githubusercontent.com/64091305/90158654-8cc4f000-dd8f-11ea-979e-80e031240155.png)

I can look into some other tools/ways if you can guide me to a direction.

**Comment by stevenschlansker** [comment] 2020-08-14 18:25
Thanks for the information.  I have found YourKit to be better than VisualVM for these sorts of things, but unfortunately it is a paid product (there is a 15 day trial license and you can apply for a free OSS license, though). 

One curious thing I see in the plots above: TransactionDecorator appears in the second profiler but not the first (unless it's cut off at the bottom).  Hard to tell if that's profiler bias or an actual problem.  But in my process of writing repeatable microbenchmarks, maybe I should start with the different ways of opening and closing Transactions.

**Comment by natan-abolafya** [comment] 2020-08-17 14:18
YourKit looks quite neat actually.

I'm uploading 2 csv files with jdbi methods calls. The test I ran was 30 logins (somewhat arbitrary considering each login has an unknown amount of jdbi operation) and 4 threads. It isn't the same as the tests as I ran where I noticed the 10-15% degradation because that requires running it somewhere stable (unlike my workstation) and more heavylifting. I'm hoping you can find something obvious in here, otherwise I can spend some more effort.

[3.12.2.txt](https://github.com/jdbi/jdbi/files/5084764/3.12.2.txt)
[3.14.1.txt](https://github.com/jdbi/jdbi/files/5084766/3.14.1.txt)

The CSV files are exported from this section:
![image](https://user-images.githubusercontent.com/64091305/90406286-3a444600-e0a5-11ea-988d-57ebd68b817d.png)

If there is a section that might be more useful, I can send that. I can also send the full snapshots in private if you think that might be more helpful.

**Comment by stevenschlansker** [comment] 2020-08-19 16:29
The CSVs are interesting but unfortunately quite difficult to parse usefully to my human brain.  Feel free to email me the snapshots privately and I can take a look.  Ultimately, I want to write reproducible benchmarks here so we can start to track these sorts of issues in a more principled manner.

**Comment by natan-abolafya** [comment] 2020-08-20 13:20
Looks like snapshot includes too much info for our proprietary software. I will try to write some jdbi specific tests instead. Will let you know when I succeed to reproduce the performance difference between versions.

**Comment by gtaborcrossword** [comment] 2020-09-01 16:53
I've just installed 3.4.14 (bundled with Dropwizard 2.0.13). Unfortunately I haven't noticed any improvement comparing to 3.13.0. So either my case is different or I measured something incorrectly. Anyway, started creating benchmark in JMH and I'll share the results with you in the next few days.

**Comment by gtaborcrossword** [comment] 2020-09-07 10:37
Hi. Here are the results with JMH benchmarking. I run the test it with the following parameters:
- 3 warmup iterations
- 4 measurement iterations, 30 seconds each
- 2 forks

and JMH produced the following summary:
```
Benchmark              Mode  Cnt  Score   Error  Units
c.jdbi2.Checker.check  avgt    8  2.987 ± 0.153  ms/op
c.jdbi3.Checker.check  avgt    8  3.254 ± 0.261  ms/op
```
So it seems that jdbi3 is a little bit slower than jdbi2, but I'm not sure, if the difference is as drastic as I noticed at the beginning.

Please take a look at the he test code: [benchmark.zip](https://github.com/jdbi/jdbi/files/5182550/benchmark.zip). Feel free to change it. Below is the full test output.

```
# JMH version: 1.19
# VM version: JDK 11.0.6, VM 11.0.6+10-LTS
# Warmup: 3 iterations, 1 s each
# Measurement: 4 iterations, 30 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: checkers.jdbi2.Checker.check

# Run progress: 0.00% complete, ETA 00:08:12
# Fork: 1 of 2
# Warmup Iteration   1: 5.646 ms/op
# Warmup Iteration   2: 4.295 ms/op
# Warmup Iteration   3: 3.354 ms/op
Iteration   1: 3.129 ms/op
Iteration   2: 3.053 ms/op
Iteration   3: 3.000 ms/op
Iteration   4: 2.928 ms/op

# Run progress: 25.00% complete, ETA 00:06:12
# Fork: 2 of 2
# Warmup Iteration   1: 4.006 ms/op
# Warmup Iteration   2: 3.527 ms/op
# Warmup Iteration   3: 3.149 ms/op
Iteration   1: 3.029 ms/op
Iteration   2: 2.942 ms/op
Iteration   3: 2.906 ms/op
Iteration   4: 2.911 ms/op

Result "checkers.jdbi2.Checker.check":
  2.987 ±(99.9%) 0.153 ms/op [Average]
  (min, avg, max) = (2.906, 2.987, 3.129), stdev = 0.080
  CI (99.9%): [2.835, 3.140] (assumes normal distribution)

# JMH version: 1.19
# VM version: JDK 11.0.6, VM 11.0.6+10-LTS
# Warmup: 3 iterations, 1 s each
# Measurement: 4 iterations, 30 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: checkers.jdbi3.Checker.check

# Run progress: 50.00% complete, ETA 00:04:08
# Fork: 1 of 2
# Warmup Iteration   1: 5.411 ms/op
# Warmup Iteration   2: 4.238 ms/op
# Warmup Iteration   3: 3.700 ms/op
Iteration   1: 3.523 ms/op
Iteration   2: 3.112 ms/op
Iteration   3: 3.228 ms/op
Iteration   4: 3.226 ms/op

# Run progress: 75.00% complete, ETA 00:02:04
# Fork: 2 of 2
# Warmup Iteration   1: 5.274 ms/op
# Warmup Iteration   2: 4.245 ms/op
# Warmup Iteration   3: 3.927 ms/op
Iteration   1: 3.370 ms/op
Iteration   2: 3.118 ms/op
Iteration   3: 3.270 ms/op
Iteration   4: 3.185 ms/op

Result "checkers.jdbi3.Checker.check":
  3.254 ±(99.9%) 0.261 ms/op [Average]
  (min, avg, max) = (3.112, 3.254, 3.523), stdev = 0.137
  CI (99.9%): [2.992, 3.515] (assumes normal distribution)

# Run complete. Total time: 00:08:18

Benchmark              Mode  Cnt  Score   Error  Units
c.jdbi2.Checker.check  avgt    8  2.987 ± 0.153  ms/op
c.jdbi3.Checker.check  avgt    8  3.254 ± 0.261  ms/op
```

**Comment by stevenschlansker** [comment] 2020-09-07 15:40
Thanks for putting together a benchmark.  It doesn't clearly indicate a problem as of yet -- the values +/- the error bars are overlapping ranges, so inconclusive.  Also, jdbi3 does a _lot_ more than jdbi2 does, so we might consider a small performance penalty worth the cost of extra features.  I will take a look at your benchmark code and maybe run it with more iterations.

**Comment by stevenschlansker** [comment] 2020-09-12 16:22
I took your benchmarks as inspiration and made #1749 
I agree, there does seem to be a performance bottleneck around the new configuration infrastructure.  It should be possible to fix.

**Comment by stevenschlansker** [comment] 2020-09-12 20:45
https://github.com/jdbi/jdbi/pull/1750

**Comment by stevenschlansker** [comment] 2020-09-12 23:02
https://github.com/jdbi/jdbi/pull/1751

**Comment by stevenschlansker** [comment] 2020-09-13 01:12
https://github.com/jdbi/jdbi/pull/1752

**Comment by stevenschlansker** [comment] 2020-09-13 19:28
https://github.com/jdbi/jdbi/pull/1753

**Comment by stevenschlansker** [comment] 2020-09-13 19:31
https://github.com/jdbi/jdbi/pull/1754

**Comment by stevenschlansker** [comment] 2020-10-01 05:04
#1766

**Comment by stevenschlansker** [comment] 2020-10-02 21:51
Hi @natan-abolafya @gtaborcrossword , could you please try out jdbi `3.15.0` and see if it improves your performance?  There's a number of improvements bundled in.

**Comment by natan-abolafya** [comment] 2020-10-05 09:54
ah, you have been in optimizing mode I see :). I tested our application with 3.15.0, and it seems there is a slight improvement of 5-10%. The benchmarking tool should say something more reliable however.

**Comment by stevenschlansker** [comment] 2020-10-16 19:43
I'm glad to hear you see the improvements.  The micro-benchmarks I wrote had much larger improvements, of course, but what matters at the end of the day is actual application performance :)

Unless there's anything more to talk about, let's call this one closed.  If there's more performance problems please do report them.

**Closed** 2020-10-16 19:43 UTC
Labels: improvement

**Comment by gtaborcrossword** [comment] 2020-10-23 11:23
I noticed ~7% improvement on the same operations that made me raise that ticket. That's great. Maybe this speedup is not astonishing but for sure decent. Thanks.

**Comment by stevenschlansker** [comment] 2020-10-23 16:59
Great!  If you take more profiles and can identify further bottlenecks, we can try for further improvements down the road.
