### ISSUE TITLE
How to map enum values containing spaces

### ISSUE THREAD

**Issue by vahidpaz** [jdbi/jdbi#1737] opened 2020-07-30 03:27 UTC
I have an enum class like:

    public enum Status {
        not_started("not started"),
        in_progress("in progress"),
        done("done");

        private String status;

        Status(String status) {
            this.status = status;
        }

        @Override
        public String toString() { return status; }
    }

JDBI fails with exception:

`org.jdbi.v3.core.result.UnableToProduceResultException: no Status value could be matched to the name not started`

When I rename the values in the db to something without spaces (e.g., "not_started") JDBI runs fine. How do I configure it in order to map correctly when having spaces?

Seems like modifying EnumMapper.java would help. Currently [line 101](https://github.com/jdbi/jdbi/blob/master/core/src/main/java/org/jdbi/v3/core/mapper/EnumMapper.java#L100) reads:
`.orElseGet(() -> comparer.test(e.name(), name));`

Changing it to the following would make my enum work:
`.orElseGet(() -> comparer.test(e.name(), name) || comparer.test(e.toString(), name));`

**Comment by stevenschlansker** [comment] 2020-08-01 19:47
Hi, the problem isn't necessarily the spaces or not, but you correctly highlight the `toString` value is not considered.  We can add this as an option.

**Comment by stevenschlansker** [comment] 2020-08-01 20:06
Ah, @vahidpaz , have you considered instead of using `toString`, using `@DatabaseValue`?  That allows you to explicitly specify the enum's value in the database.

**Comment by hanzo2001** [comment] 2020-09-21 17:43
@stevenschlansker, @vahidpaz  I had an issue with my enums having custom Int values (I'm working with Kotlin).

I used a custom ColumnMapper for my specific enum type.

Here's the link to my [StackOverflow answer](https://stackoverflow.com/a/63997274/2733184)

Would you consider my solution as an appropriate use of a custom column mapper? Can this be done in a better way?

**Comment by stevenschlansker** [comment] 2020-09-22 01:14
@hanzo2001, I'm unfortunately not very familiar with Kotlin personally, but registering a custom `ColumnMapper<N>` to handle logic specific to the `N` type is exactly what you're supposed to do.  The core logic present in Jdbi doesn't map to custom Enum properties like you have right now.  This issue is to add support for configurable core logic for `toString`, which is almost exactly like your use case, except that of course the value must be a `String`, so it would not help you.

**Comment by stevenschlansker** [comment] 2023-09-29 16:47
Closing as answered, we can re-open if there's more followup.

**Closed by stevenschlansker** 2023-09-29 16:47 UTC
Labels: feature
