### ISSUE TITLE
bindNamed() is too restrictive about requiring named parameters if binding is present.

### ISSUE THREAD

**Issue by rjnay** [jdbi/jdbi#1175] opened 2018-06-12 19:15 UTC
We are using a conditional statement as follows, that causes and exception within bindNamed() when the condition is false. Why not change bindNamed to just return if parameterNames is empty?

```
@SqlQuery("select * from table_name <if(boolean_variable)> where id = :id <endif>")
@UseStringTemplateEngine
public  abstract List<SomeClass> query(@Define("boolean_variable") Boolean boolean_variable,
        @Bind("id") String id);
```

bindNamed() snippet for reference.

```
private static void bindNamed(List<String> parameterNames, Binding binding, PreparedStatement statement, StatementContext context) {
    if (parameterNames.isEmpty() && !binding.isEmpty()) {
        throw new UnableToExecuteStatementException(
            String.format("Unable to execute. The query doesn't have named parameters, but provided binding '%s'.", binding),
            context);
    }
```

**Comment by TheRealMarnes** [comment] 2018-06-13 17:55
I don't speak for the other devs, but I would leave it as it is for the principle of fail-fast. If a variable is placed on some context, that means it's intended to be used. A simple typo or other bug could then cause the variable to not be bound, leading to execution of code that isn't what was intended. Tools should prevent that rather than encouraging it.

Enabling the behavior you want has the potential to cause great problems, while not enabling it is only a minor inconvenience in certain ways of using the API. Jdbi overall follows a philosophy of being as strict as possible, and failing hard when something isn't clearly defined, IMO.

If you want to use this kind of thing, you could implement your own SqlParser based on the jdbi source code that skips the relevant check, or file a request here to enable something like Angular's optional variable syntax, like `where id = :id? <endif>`, with `?` denoting optionality.

**Comment by stevenschlansker** [comment] 2018-06-14 17:54
I think you might misunderstand, @TheRealMarnes .
It looks like the issue is that a statement that sometimes takes a bound parameter, and sometimes does not, because we assume that "binding parameters but none bound" is an error.
I haven't dug in extensively but we could consider relaxing this, or making it configurable.

**Comment by TheRealMarnes** [comment] 2018-06-14 17:59
@stevenschlansker you sure? I understood that

`"select * from table_name <if(maybe)> where id = :id <endif>"` will be processed with `@Define boolean maybe` and `@Bind int id`.

And it will throw an error if `maybe = false` because the templateEngine will reduce the string to `"select * from table_name"`, which leaves `id` sitting in the Binding without a place in the query to be bound to, which we check for.

And @rjnay wants to enable variables to be `@Bind`ed without necessarily having to be bound to the final query string.

**Comment by TheRealMarnes** [comment] 2018-06-14 18:02
> this error happens when

Oh yeah, the templateEngine would already have removed it so the SqlParser wouldn't see the `?` that denotes optionality...

I think, if we want to add optionality, it'll have to be a general setting on `SqlStatements`, a property on `@Bind` instances, use of `Optional<T>` (though I smell use case conflicts here), or a custom `org.jdbi.MaybeBind<T>` type...

**Comment by kaandok** [comment] 2018-07-10 21:23
this makes life easier with some conditional queries using template engines, could we get this merged into the new release?

**Comment by TheRealMarnes** [comment] 2018-07-10 21:38
merge conflicts fixed

plis murdge

**Comment by stevenschlansker** [comment] 2018-09-07 19:15
will be in 3.5.0

**Closed by stevenschlansker** 2018-09-07 19:15 UTC
Labels: improvement
