### ISSUE TITLE
Ignore @JdbiConstructor on Kotlin synthetic constructors

### ISSUE THREAD

**Issue by ecdpalma** [jdbi/jdbi#1295] opened 2018-10-30 17:34 UTC
When annotating a data class constructor with JdbiConstructor, the Kotlin compiler annotates both the declared constructor and the synthetic one, causing Jdbi to complain about two annotated constructors.

**Comment by TheRealMarnes** [comment] 2018-10-30 23:13
I don't know kotlin, but I can tell JdbiConstructor is really not meant to appear more than once because it points out a preferred constructor. Can you prevent the annotation on the synthetic constructor, e.g. by explicitly declaring it?

**Comment by ecdpalma** [comment] 2018-10-31 17:10
> Can you prevent the annotation on the synthetic constructor, e.g. by explicitly declaring it?

Maybe, I haven't tested yet. I'll try and post here.

There's an open issue in Jetbrains tracker, but it's old (https://youtrack.jetbrains.com/issue/KT-10049). Also, jackson-databind had the same problem back then (https://github.com/FasterXML/jackson-databind/issues/1005). They fixed it by skipping synthetic things.

**Comment by TheRealMarnes** [comment] 2018-10-31 19:43
@ecdpalma could you test if isSynthetic allows us to detect the method you're talking about? I assume it means methods generated at compile time without having been explicitly written. I don't know kotlin so someone else should test it.

**Comment by stevenschlansker** [comment] 2018-11-02 19:52
Ignoring annotations on synthetic constructors is reasonable, and I suspect it will solve this issue nicely.

**Comment by ecdpalma** [comment] 2018-11-03 00:42
I've done some tests here and found that problem does not happen in simple classes, but it happens when annotating a method with @RegisterConstructorMappers, on a master-detail join query.

E.g

```
data class Cart @JdbiConstructor constructor(
  ...
  val items: List<Item> = mutableList()
)

data class Item @JdbiConstructor constructor(
  ...
)

@RegisterConstructorMappers(
  RegisterConstructorMapper(value = Cart::class, prefix = "c"),
  RegisterConstructorMapper(value = Item::class, prefix = "i")
)

@UseRowReducer(value = Reducer::class)
@SqlQuery("SELECT ...")
fun findCart(id: Long): Cart
```

As a workaround, I registered the mappers in code, like this https://gist.github.com/mustafo/36e9f754aaefc85924eb0ddc276d970e.

**Comment by TheRealMarnes** [comment] 2018-12-14 15:41
@ecdpalma I'm having a look at this but I don't quite know kotlin. I tried this test:

```
    data class DataClassWithSingleAnnotation
    @JdbiConstructor
    constructor (val id : Int, val first : String, val second : String, val third : String)

    @Test
    fun testDataClass() {
        oneTwoThreeFourSetup()

        val result = handle.createQuery(oneTwoThreeFourQuery)
            .mapTo<DataClassWithSingleAnnotation>()
            .first()

        assertThat(result.first).isEqualTo(one)
        assertThat(result.second).isEqualTo(two)
        assertThat(result.third).isEqualTo(three)
    }
```

It's green, so I'm guessing this is not quite the same as your use case. Could you correct the test case so we can write a fix, please? Or submit a PR if you feel adventurous...

**Comment by TheRealMarnes** [comment] 2018-12-16 21:51
@ecdpalma I published a wip branch https://github.com/jdbi/jdbi/tree/%231295-kotlin-constructors with my test and potential fix, could you please check it out and PR the corrected test (and the fix if you can)?

**Comment by ecdpalma** [comment] 2018-12-18 23:20
@TheRealMarnes i could not replicate the case in jdbi tests, neither with your test nor mine. I'll have to check my real project setup.

FYI: this is similar to my real case:

   
    @Rule @JvmField
    val db = H2DatabaseRule()
        .withPlugin(SqlObjectPlugin())
        .withPlugin(KotlinPlugin())
        .withPlugin(KotlinSqlObjectPlugin())

    data class DataClassWithJdbiConstructor @JdbiConstructor constructor(val s: String, val i: Int)

    interface TestDao {
        @SqlQuery("SELECT s as s, i as i from bean where s = :s")
        @RegisterConstructorMappers(
            RegisterConstructorMapper(DataClassWithJdbiConstructor::class)
        )
        fun findOne(s: String): DataClassWithJdbiConstructor
    }

    @Test
    fun testDataClassWithJdbiConstructor() {
        db.sharedHandle.execute("CREATE TABLE bean (s varchar, i integer)")

        db.sharedHandle.execute("INSERT INTO bean VALUES('3', 2)")

        var dao = db.jdbi.onDemand(TestDao::class.java)

        val result = dao.findOne("3")

        assertThat(result.s).isEqualTo("3")
        assertThat(result.i).isEqualTo(2)
    }

**Comment by qualidafial** [comment] 2019-01-08 18:14
@TheRealMarnes Column name in the annotation needs to be different from the constructor parameter name to be a valid test of `@ColumnName` support

**Comment by TheRealMarnes** [comment] 2019-01-08 19:49
@qualidafial test updated, it's still green ¯\\\_(ツ)\_/¯

**Comment by ecdpalma** [comment] 2019-01-09 13:38
@TheRealMarnes Sorry for the delay. As I said before, I could not replicate, only in production code, which is similar to the test I pasted above. I think there's some issue with my environment (Kotlin version?), not sure.

**Comment by TheRealMarnes** [comment] 2019-01-27 19:07
@ecdpalma do you have any new information or do you think we can close this as a false alarm?

**Comment by vaclavhodek** [comment] 2019-02-21 16:03
To test this problem, you have to specify default values in your data class. 

It's gonna be green for:
```kotlin
data class DataClass(
	@ColumnName("s") val s: String, 
	@ColumnName("i") val i: Int
)
```
No synthetic constructors are created by Kotlin in this case.

However, once you add default value, Kotlin has to generate synthetic constructors for all possible variants.
```kotlin
data class DataClass(
	@ColumnName("s") val s: String, 
	@ColumnName("i") val i: Int = 5
)
```
So the code above is no longer green if you use `@RegisterConstructorMapper`. You end up with `class DataClass must have exactly one constructor, or specify it with @JdbiConstructor or @ConstructorProperties` and using `data class DataClass @JdbiConstructor constructor(...)` doesn't solve the problem as annotations are unconditionally copied to synthetic constructors as well. 

To solve the problem, it's necessary to skip synthetic constructors.

**Comment by TheRealMarnes** [comment] 2019-02-21 16:31
Thanks @vaclavhodek , gonna PR the fix really soon

**Comment by vaclavhodek** [comment] 2019-02-21 16:53
Awesome! Thanks for so quick fix!

**Comment by TheRealMarnes** [comment] 2019-02-21 16:55
I've had the fix ready for months, I was just waiting for the test case 😛 Sucks that it was such a tiny detail I didn't get

**Comment by vaclavhodek** [comment] 2019-02-21 17:17
I'm glad that I could help you. It took me some time to find the problem too but I know Kotlin quite well, and I was aware of some internal mechanics, so it wasn't so hard to guess where the problem is. 

It's a bit puzzling problem if you don't know both languages well as it doesn't make sense isolated - it should not happen in Java, and the error message doesn't make sense in Kotlin unless you are aware how the Kotlin code is translated to JVM bytecode.

**Comment by TheRealMarnes** [comment] 2019-02-22 09:46
There's a naggy voice in my head telling me to check if the same thing needs to happen for static factory methods...

**Closed** 2019-02-22 20:53 UTC
Labels: bug, help wanted

**Comment by hjizettle** [comment] 2022-04-05 05:58
This class seems to still have this problem:

```java
private static <T> Constructor<T> findImplicitConstructorFor(Class<T> type) {
        @SuppressWarnings("unchecked")
        final Constructor<T>[] constructors = (Constructor<T>[]) type.getDeclaredConstructors();

        List<Constructor<T>> annotatedConstructors = Stream.of(constructors)
                .filter(c -> c.isAnnotationPresent(ConstructorProperties.class))
                .collect(Collectors.toList());

        if (annotatedConstructors.size() > 1) {
            throw new IllegalArgumentException(type + " may have at most one constructor annotated @ConstructorProperties");
        } else if (annotatedConstructors.size() == 1) {
            return annotatedConstructors.get(0);
        }

        if (constructors.length != 1) {
            throw new IllegalArgumentException(type + " must have exactly one constructor, or specify it with @JdbiConstructor or @ConstructorProperties");
        }
        return constructors[0];
    }
```

When I use `@ConstructorProperties` I get the synthetic constructor and `@JdbiConstructor` gives none of the constructors. It seems the code doesn't even care about the latter or filters out synthetic constructors.

Was there really a fix release for this? I am on `3.28.0`.

**Comment by hjizettle** [comment] 2022-04-05 06:42
It works for me when I annotate with `@JdbcConstructor` on a static (`@JvmStatic` companion object) factory method but I really think it should work for Regular constructors too which it would if the synthetic methods get filtered out everywhere it's relevant.

**Comment by ecdpalma** [comment] 2024-04-27 14:44
Late feedback: I can't reproduce this with 3.45.0 (almost six years, still using this lib, thank you).
