### ISSUE TITLE
Document @Transaction annotation

### ISSUE THREAD

**Issue by ahamid** [jdbi/jdbi#86] opened 2013-12-03 07:17 UTC
It would be great to have some documentation on the @Transaction annotation. I just lost several hours of debugging to find @Transaction handling was behaving exceedingly unintuitively.

My end goal was to hand-write a dynamic query but join an existing wrapping transaction started explicitly by a unit test:

```
@Before
h.begin()

@After
h.rollback

@Test
userDao.getUserMoreComplicated(...)

public interface MyDAO implements GetHandle {
  @SqlQuery("thought this was transactional...")
  @Transaction // nope.
  public User getUser(@Bind("id") String id);

  @Transaction // does not join existing transaction either...
  public User getUserMoreComplicated(String arg1, Integer arg2, etc.) {
    return withHandle(new HandleCallback<User>() {
      public User withHandle(Handle handle) throws Exception
      {
        return  handle.createQuery("my super duper dynamically constructed query").map(User.class).list(); 
      }
    }
  }
}
```

What I found was that `getUserMoreComplicated` was always committing, while `getUser` was apparently correctly rolling back (not committing).  Similarly, explicitly using `handle.withTransaction` resulted in commit.  And leaving them all off naturally resulted in no transactionn and no rollback if no wrapping transaction was explicitly set up.

There are several things wrong here.  To start `getUser` was not working as I assumed.  It turns out that _`@Transaction` is mutually exclusive with every other annotation_.  See below in SqlObject:

``` SqlObject
// these else ifs are all mutually exclusive...
for (final ResolvedMethod method : d.getMemberMethods()) {
    final Method raw_method = method.getRawMember();

    if (raw_method.isAnnotationPresent(SqlQuery.class)) {
        handlers.put(raw_method, new QueryHandler(sqlObjectType, method, ResultReturnThing.forType(method)));
    }
    else if (raw_method.isAnnotationPresent(SqlUpdate.class)) {
        handlers.put(raw_method, new UpdateHandler(sqlObjectType, method));
    }
    else if (raw_method.isAnnotationPresent(SqlBatch.class)) {
        handlers.put(raw_method, new BatchHandler(sqlObjectType, method));
    }
    else if (raw_method.isAnnotationPresent(SqlCall.class)) {
        handlers.put(raw_method, new CallHandler(sqlObjectType, method));
    }
    else if(raw_method.isAnnotationPresent(CreateSqlObject.class)) {
        handlers.put(raw_method, new CreateSqlObjectHandler(raw_method.getReturnType()));
     }
     else if (method.getName().equals("close") && method.getRawMember().getParameterTypes().length == 0) {
         handlers.put(raw_method, new CloseHandler());
     }
     else if (raw_method.isAnnotationPresent(Transaction.class)) {
         handlers.put(raw_method, new PassThroughTransactionHandler(raw_method, raw_method.getAnnotation(Transaction.class)));
     }
     else if (mixinHandlers.containsKey(raw_method)) {
         handlers.put(raw_method, mixinHandlers.get(raw_method));
     }
     else {
         handlers.put(raw_method, new PassThroughHandler(raw_method));
     }
}
```

You can't have `@Transaction @SqlUpdate` or `@Transaction @SqlQuery`, it just doesn't work like Spring transactions.  Secondly, this explains why `getUserMoreComplicated` was always committing.  `@Transaction` is the only annotation present on that method, so `@Transaction` functionality is enabled, and what this actually does is unilaterally commit:

``` LocalTransactionHandler.inTransaction
 try {
     handle.begin();
     returnValue = callback.inTransaction(handle, status);
     if (!failed.get()) {
         handle.commit();
     }
}
```

Could it be I missed critical docs on `@Transaction`?  At the very least its scope of functionality seems very counter-intuitive to me, and probably anybody coming from a declarative transaction background.  Is the intent really for `@Transaction` to _not_ apply to SQL Object methods, and for it to forcefully commit?  If so, is there any way at all to write reusable code that joins an existing transaction (e.g. unit tests) or starts a new one on demand (production)?

**Comment by Manikandan-K** [comment] 2015-05-10 11:08
I have documented it here. 
http://manikandan-k.github.io/2015/05/10/Transactions_in_jdbi.html
See whether it helps.

**Comment by pandaadb** [comment] 2015-10-22 15:41
Hey, 

I am not sure if this is the right place to put this (I can open a new issue) but there seems to be a bug with transaction handling. Or if not, this is a trap and also needs documentation: 

Case a: 

If you try to execute transactions on methods that have an annotation, new transaction context is created and forgets about the parent. For example: 

@Transaction public void methodA() { ...} 
@Transaction public void methodB() { ...} 
@Transaction public void methodC() { ...} 

@Transaction public void doALot() {
  methodA()
  methodB()
  methodC()
{

This will create 4 Transaction contexts. The problem is, if method C throws an Exception, ONLY method C is rolled back. Method "doALot" will be rolled back too, but since A and B have been committed and the transaction closed, those updates are now solid. 
Each transaction seems to indicate that a new transaction context is created and the parent one is forgotten. This seems highly unintuitive to me, as I would expect that ALL is wrapped in the same transaction.

The above example correctly rolls back if @Transaction is removed from A, B and C. The issue with this is, that one has to write a lot of extra code in some cases. For example, if A and B MUST be in transaction, that means that the methods inside need to be split out to something else so that they can be called from D to be wrapped in the same transaction. 

Artur

**Comment by stevenschlansker** [comment] 2015-10-22 20:33
Dang, this is confusing.  As of #165 and #166 we now explicitly disallow this case, rather than silently doing the wrong thing.  So hopefully that is some kind of improvement.

I think asking for Spring-style nested transactions is fundamentally reasonable, just needs someone to write out support for it.  I don't think it would actually be all that hard.

Having it exclusive with any other annotations definitely sucks.  That's probably yet another fixup we need to do.

Sorry to not have a fix for you right now, I'm rather busy at work, but if nobody else picks it up I'll try to look at it soon.

**Comment by stevenschlansker** [comment] 2015-10-22 20:43
Filed a couple of separate feature requests, we'll leave this one as tracking documentation updates as it was originally opened as.

**Comment by deeTEEcee** [comment] 2016-09-06 18:21
don't understand why this annotation has absolutely no documentation at all since transactions are pretty important in the db flow of things. im assuming its rather different from spring's transactional and while logically, i know how transactions work, i hesitate a little when doing things like "can i throw ANY kind of exception and it'll rollback or do i have to throw a specific type of exception?"

**Comment by stevenschlansker** [comment] 2016-09-06 19:53
hi @deeTEEcee unfortunately proper documentation for this sort of thing has historically been a weak point of the project.  We're working on improving that situation for the upcoming v3 release, and a fair amount of it is very applicable to v2 as well: http://jdbi.github.io/

The short answer is, any thrown exception will rollback a transaction.  When in doubt, consult the code: https://github.com/jdbi/jdbi/blob/master/src/main/java/org/skife/jdbi/v2/tweak/transactions/LocalTransactionHandler.java#L170-L213  😄

**Comment by deeTEEcee** [comment] 2016-09-06 22:15
@stevenschlansker ah okay, appreciate the quick response! unfortunately, java annotations are kind of my weak point and i wasn't sure where to see how it applies in the code other than assuming the magic works. I guess I'll get to understanding that now :P.

**Comment by stevenschlansker** [comment] 2016-09-06 23:19
Yes, annotations are intentionally pretty magical.  I find that aggressive use of my IDE's "find uses of" works pretty well -- e.g. if you find uses of the `@Transaction` type it leads you to `PassThroughTransactionHandler` where the actual implementation goes to.  And if you have any questions like this, the user list is often fairly responsive.

**Comment by stevenschlansker** [comment] 2018-03-31 01:38
It's [now documented](http://jdbi.org/#_transaction_management) :smiley_cat:

**Closed by stevenschlansker** 2018-03-31 01:38 UTC
Labels: doc, help wanted
