### ISSUE TITLE
Throw exception when attempting to configure generated keys after statement has been created

### ISSUE THREAD

**Issue by zikani03** [jdbi/jdbi#813] opened 2017-05-19 04:15 UTC
This might just be an issue of documentation. Currently, the 
documentation in the `beforeExecution` of StatementCustomizer says:

```
Make the changes you need to inside this method. 
It will be invoked prior to execution of the prepared statement
```

However, as far as I can tell those changes do not apply for the 
context's setReturningGeneratedKeys(boolean) and setGeneratedKeysColumnNames(String...) methods.

Example code:

```java
public class Application {

    public static void main(String... args) throws Exception {
        Class.forName("org.postgresql.Driver");
        String url = "jdbc:postgresql://localhost:5432/database",
            user = "user",
            password = "password";
        Handle handle = Jdbi.open(url, user, password);

        handle.execute("CREATE TABLE posts(id serial primary key, user_id integer,  content varchar(255));");
        // Changing the generated keys configuration on the context from a statement works
        Update update =  handle.createUpdate("INSERT INTO posts(content, user_id) VALUES (:content, :author_id)");

        update.getContext().setReturningGeneratedKeys(true);
        update.getContext().setGeneratedKeysColumnNames(new String[] { "id" });

        String withoutCustomizer = update
                .bind("content", "Yay! Post content!")
                .bind("author_id", 1)
                .execute(Application::resultProducer);

        System.out.println("Generated Value is: " + withoutCustomizer); // Generated Value is: 1

        // This will throw an UnableToProduceResultException
        String withCustomizer = handle.createUpdate("INSERT INTO posts(content, user_id) VALUES (:content, :author_id)")
                .addCustomizer(new SimpleCustomizer())
                .bind("content", "Yay! Post content!")
                .bind("author_id", 1)
                .execute(Application::resultProducer);

        System.out.println("Generated Value is: " + withCustomizer);

        handle.close();
    }

    private static String resultProducer(Supplier<PreparedStatement> supplier, StatementContext ctx) throws SQLException{
        PreparedStatement statement = supplier.get();

        ResultSet rs = statement.getGeneratedKeys();

        if (rs == null) {
            return "No Generated Keys";
        }
        rs.next();
        return String.valueOf(rs.getInt("id"));
    }

    private static class SimpleCustomizer implements  StatementCustomizer {

        @Override
        public void beforeExecution(PreparedStatement stmt, StatementContext ctx) throws SQLException {
            ctx.setReturningGeneratedKeys(true);
            ctx.setGeneratedKeysColumnNames(new String[] { "id" });
        }
    }
}
```

**Comment by qualidafial** [comment] 2017-05-22 22:45
As an aside: If a result producer invokes `supplier.get()`, it is responsible for closing the statement--which cleans up database resources.

**Comment by qualidafial** [comment] 2017-05-22 23:09
@zikani03 This is not a bug--at least not in Jdbi itself.

There are several overloaded methods in `java.sql.Connection` that Jdbi has to choose between, depending on whether we are returning generated keys. This means that `setReturningGeneratedKeys()` must be called _before_ the statement is even created--by the time statement customizers are being processed, it's too late.

Jdbi provides a ResultProducer out of the box that handles this for you:

```java
String withBuiltInApis = handle.createUpdate(
        "INSERT INTO posts(content, user_id) VALUES (:content, :author_id)")
    .bind("content", "Yay! Post content!")
    .bind("author_id", 1)
    .execute(ResultProducers.returningGeneratedKeys("id"))
    .mapTo(String.class)
    .findOnly();
```

Based on this, I think it would be valuable to add a check in `StatementContext`, and throw an exception if you try to call `setReturningGeneratedKeys()` or `setGeneratedKeysColumnNames()` after the `PreparedStatement` has been instantiated.

**Comment by qualidafial** [comment] 2017-05-22 23:15
Also, Update has a method which is explicitly for generated keys: `Update.executeAndReturnGeneratedKeys("id")`

**Comment by zikani03** [comment] 2017-05-29 09:30
Sorry for the late response. Thanks for the feedback. I wasn't aware of that method on the ResultProducers. 👍 

I realize now that I didn't state the issue properly - what I wanted to get at is that, right now, there is no way to get the actual value of generated keys from within a statement customizer without going through the PreparedStatement itself - which seems like a hack and source of bugs e.g.  not releasing resources as you noted in comment above:

> As an aside: If a result producer invokes supplier.get(), it is responsible for closing the statement context--which cleans up database resources.

I agree with with regard to throwing an exception if the PreparedStatement is already  instantiated.

**Closed** 2022-08-03 20:32 UTC
Labels: improvement
