### ISSUE TITLE
Getting IllegalStateException: Unable to instantiate config class class org.jdbi.v3.core.statement.SqlStatements. Is there a public no-arg constructor?

### ISSUE THREAD

**Issue by jayaraj** [jdbi/jdbi#1537] opened 2019-06-02 06:55 UTC
Hi,
     I was trying to test a few examples with JDBI v3 (attached the test code below). I am not able to understand what I missed in the implementation. Can you please help why I am getting this Exception.

java.lang.IllegalStateException: Unable to instantiate config class class org.jdbi.v3.core.statement.SqlStatements. Is there a public no-arg constructor?
	at org.jdbi.v3.core.config.ConfigRegistry.get(ConfigRegistry.java:64)
	at org.jdbi.v3.core.config.Configurable.getConfig(Configurable.java:68)
	at org.jdbi.v3.core.statement.BaseStatement.getCustomizers(BaseStatement.java:88)
	at org.jdbi.v3.core.statement.BaseStatement.callCustomizers(BaseStatement.java:78)
	at org.jdbi.v3.core.statement.SqlStatement.beforeTemplating(SqlStatement.java:1588)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1519)

@RunWith(SpringRunner.class)
@SpringBootTest (classes = TestContextConfiguration.class)
public class ExampleTestJdbi {
	@Test
	  public void test() {
		Jdbi jdbi = Jdbi.create("jdbc:h2:mem:test");
		jdbi.installPlugin(new SqlObjectPlugin());
		AccountDao dao = jdbi.onDemand(AccountDao.class);
		dao.createTable();
		dao.insert(new Account(1, "Alice"));
		dao.insert(new Account(2, "Bob"));
	}
	
	@RegisterBeanMapper(Account.class)
	@RegisterRowMapper(AccountMapper.class)
	public interface AccountDao {
	    @SqlUpdate("create table accounts (id bigint primary key, name varchar(100))")
	    void createTable();

	    @SqlUpdate("insert into accounts (id, name, balance) values (:id, :name)")
	    void insert(@BindBean Account accounts);

	    @SqlUpdate("update accounts set name = :name where id = :id")
	    void update(@BindBean Account accounts);

	    @SqlQuery("select * from accounts order by id")
	    List<Account> list();

	    @SqlQuery("select * from accounts where id = :id")
	    Account getById(int id);
	  }
	
	@Value
	public static class Account {
	    private Long id;
	    private String name;
	    
	    public Account() {
	    	this.id = null;
		      this.name = null;
	    }

	    public Account(long id, String name) {
	      this.id = id;
	      this.name = name;
	    }
	}
	
	public static class AccountMapper implements RowMapper<Account> {
		@Override
		public Account map(ResultSet rs, StatementContext ctx) throws SQLException {
			int id = rs.getInt("id");
	       String name = rs.getString("name");
			return new Account(id, name);
		}
	}
}

**Comment by TheRealMarnes** [comment] 2019-06-02 11:20
Which version of jdbi is this? I recall a recently fixed exception in that area.

**Comment by jayaraj** [comment] 2019-06-02 11:24
3.8.2

**Comment by TheRealMarnes** [comment] 2019-06-02 11:31
Alright, we'll look deeper into it asap. I'm busy right now myself though so no promises on the time.

The `@Value` is Immutables?

**Comment by jayaraj** [comment] 2019-06-02 11:35
No, lombok

**Comment by stevenschlansker** [comment] 2019-06-02 16:22
Strange, `SqlStatements` of course does have such a constructor:
https://github.com/jdbi/jdbi/blob/master/core/src/main/java/org/jdbi/v3/core/statement/SqlStatements.java#L43

Is there any additional information attached to the rest of the exception, in particular, it should have a "caused by" exception attached.  That will give us more information as to what the problem is.

**Comment by jayaraj** [comment] 2019-06-03 05:27
I don't what was wrong, now am not able to reproduce the same Exception. I am attaching the Project files.

Try the test files defined under the project

[db.zip](https://github.com/jdbi/jdbi/files/3245967/db.zip)

**Comment by stevenschlansker** [comment] 2019-06-06 18:15
I am not able to download the linked project.  If you're not able to reproduce this issue, I am going to close it, but please feel free to follow up if there's additional developments.

**Closed by stevenschlansker** 2019-06-06 18:15 UTC
Labels: bug
