### ISSUE TITLE
Exception thrown when binding argument of supported type.

### ISSUE THREAD

**Issue by edwinnyawoli** [jdbi/jdbi#994] opened 2017-12-29 18:34 UTC
I'm trying to insert a bean into an sqlite database. The bean has a url field of type URL. When I try inserting it into the database i get this error:

````java
Exception in thread "main" org.jdbi.v3.core.statement.UnableToCreateStatementException: Exception while binding named parameter 'url' [statement:"INSERT INTO book (title, url) VALUES (:title, :url);", rewritten:"INSERT INTO book (title, url) VALUES (:title, :url);", parsed:"ParsedSql{sql='INSERT INTO book (title, url) VALUES (?, ?);', parameters=ParsedParameters{positional=false, parameterNames=[title, url]}}", arguments:{ positional:{}, named:{}, finder:[{lazy bean property arguments "jdbc.Book@5f3a4b84"]}]
	at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:63)
	at org.jdbi.v3.core.statement.ArgumentBinder.bind(ArgumentBinder.java:27)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1443)
	at org.jdbi.v3.core.result.ResultProducers.lambda$returningUpdateCount$0(ResultProducers.java:39)
	at org.jdbi.v3.core.statement.Update.execute(Update.java:53)
	at org.jdbi.v3.core.statement.Update.execute(Update.java:41)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$new$2(SqlUpdateHandler.java:56)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$configureReturner$3(SqlUpdateHandler.java:69)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:155)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.invoke(SqlUpdateHandler.java:29)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:162)
	at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:73)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:161)
	at com.sun.proxy.$Proxy4.addBook(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$null$0(OnDemandExtensions.java:60)
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:464)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$create$1(OnDemandExtensions.java:57)
	at com.sun.proxy.$Proxy4.addBook(Unknown Source)
````
Here are my dao interface and bean class

````java
public interface BookDao {
    @SqlUpdate("CREATE TABLE IF NOT EXISTS book (" +
            "id INTEGER PRIMARY KEY, " +
            "title TEXT, " +
            "url TEXT);")
    void createTableIfNotExits();

    @SqlQuery("SELECT * FROM book;")
    @RegisterConstructorMapper(Book.class)
    List<Book> getAllBooks();

    @SqlUpdate("INSERT INTO book (title, url) VALUES (:title, :url);")
    boolean addBook(@BindBean Book book);

    @SqlUpdate("DELETE FROM book WHERE id=:id;")
    boolean removeBooks(@BindBean Book book);
}
````

````java
public class Book {
    private final int id;
    private String title;
    private URL url;

    public Book(@ColumnName("id") int id, @ColumnName("title") String title, @ColumnName("url") URL url) {
        this.id = id;
        this.title = title;
        this.url = url;
    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public URL getUrl() {
        return url;
    }
}
````

According to the documentation, URL is a supported type so i'm thinking it would automatically be mapped to a string for me. Am I doing something wrong?

**Comment by qualidafial** [comment] 2017-12-29 21:36
Can you post the `Caused by:` part of your stack trace?

**Comment by edwinnyawoli** [comment] 2017-12-29 22:54
````java
Caused by: java.sql.SQLException: not implemented by SQLite JDBC driver
	at org.sqlite.jdbc3.JDBC3PreparedStatement.unused(JDBC3PreparedStatement.java:499)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.setURL(JDBC3PreparedStatement.java:516)
	at org.jdbi.v3.core.argument.BuiltInArgumentFactory$BuiltInArgument.apply(BuiltInArgumentFactory.java:192)
	at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:60)
	... 22 more
````

**Comment by stevenschlansker** [comment] 2017-12-29 23:03
The most obvious fix is that SQLite should implement this method which is part of JDBC spec.
As a workaround, we could add a SQLite plugin that instead understands to bind these simply as `varchar`.

**Comment by edwinnyawoli** [comment] 2017-12-29 23:09
That would be great.
Currently I'm implementing and registering an ArgumentFactory for URL types.

**Comment by stevenschlansker** [comment] 2017-12-29 23:13
That's essentially the start of the plugin I'm referring to, if you'd like to contribute it as such that should be an easy PR :)

**Comment by edwinnyawoli** [comment] 2017-12-29 23:17
Getting on that asap :)

**Comment by edwinnyawoli** [comment] 2017-12-30 19:23
I've issued a pull request. Are there any suggestions?

**Comment by qualidafial** [comment] 2017-12-31 19:42
Looks great! I reviewed the PR and left some comments.

Closing this issue in favor of #995

**Closed by qualidafial** 2017-12-31 19:42 UTC
Labels: bug, driver
