### ISSUE TITLE
DB2 Blob is returned as a com.ibm.db2.jcc.am.c6 object

### ISSUE THREAD

**Issue by trsrc** [jdbi/jdbi#1654] opened 2020-01-29 16:28 UTC
Hi,
inserting a byte array into a blob column works fine, but when reading from the DB you receive a IBM c6 object (form IBM jdbc driver).

It seems it is possible to convert to a byte array with the below code. 
I'm not sure how could I use this with ArgumentFactory or ColumnMapper?

```java
private static byte[] db2Blob(final c6 blob)
	{
		byte[] byteArr = null;
		try
		{
			commpressedFile = new byte[blob.getBinaryStream().available()];
			blob.getBinaryStream().read(byteArr);
		}
		catch (final SQLException | IOException e)
		{
			e.printStackTrace();
		}

		return byteArr;
	}
```

**Comment by stevenschlansker** [comment] 2020-02-12 02:04
Hi @trsrc , when you implement a new mapped type, you might want to implement the `ColumnMapperFactory` interface.  From there you inspect the type and in this case look for `byte[]`.  If it matches, return a `ColumnMapper` that unpacks the `c6` datatype and returns a `byte[]`.  If this is a problem all users of DB2 will have we can consider adding a DB2 module to jdbi with the fix.

**Comment by stoyants** [comment] 2024-02-05 23:00
I can't reproduce this problem with DB2 Block returning "c6" class (yes, IBM obfuscate their Java code, that's why classes and methods have weird names)
In fact I added a new testcontainer test class, for DB2 databases, with a dedicated test for blobs.
The code can be found here: https://github.com/stoyants/jdbi/tree/testcontainers-db2
@stevenschlansker if interested, I can make a MR and add the DB2 testcontainer to primary JDBI repo.
And I suggest to close this issue.

**Comment by stevenschlansker** [comment] 2024-02-05 23:04
Thank you! Yes, we'd be happy to accept additional tests that verify DB2 and in particular returning `byte[]`.

We would probably mark it as a "slow" test since it takes so long to run. But it is still valuable.

If anyone still finds this to be a problem, please reopen or comment in this issue and we can follow up.

**Closed by stevenschlansker** 2024-02-05 23:04 UTC
Labels: question

**Comment by stoyants** [comment] 2024-02-05 23:07
It is already tagged as "slow" :)
