### ISSUE TITLE
NullPointerException at sun.reflect.annotation.TypeAnnotationParser.mapTypeAnnotations

### ISSUE THREAD

**Issue by animesh-sharama** [jdbi/jdbi#1552] opened 2019-07-04 21:24 UTC
jdbi3 throws NPE when using mariaDB client.

steps to reproduce

- create a dropwizard maven project with below as dependency

```
<properties>
        <dropwizard.version>1.3.12</dropwizard.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

<dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
            <version>${dropwizard.version}</version>
 </dependency>

<dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>2.4.2</version>
        </dependency>

<dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-jdbi3</artifactId>
            <version>2.0.0-rc4</version>
</dependency>
```

- try building and running the project (mvn package; java -jar.....)

The exact same config with hibernate works fine
replace the jdbi3 dependency with hibernate, rebuild and rerun the error is gone.
```
<dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-hibernate</artifactId>
            <version>${dropwizard.version}</version>
</dependency>
```

**Comment by TheRealMarnes** [comment] 2019-07-04 21:29
Reporting an NPE but not including the java/sql code that triggers it, or the stacktrace you get, really gives us little to work with without going through setting this up on good faith... Please include the stacktrace and any relevant code at least, they should be easily accessible to you.

**Comment by animesh-sharama** [comment] 2019-07-04 22:01
stackTrace

```
java.lang.NullPointerException
        at sun.reflect.annotation.TypeAnnotationParser.mapTypeAnnotations(TypeAnnotationParser.java:356)
        at sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl.<init>(AnnotatedTypeFactory.java:139)
        at sun.reflect.annotation.AnnotatedTypeFactory.buildAnnotatedType(AnnotatedTypeFactory.java:65)
        at sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedType(TypeAnnotationParser.java:79)
        at java.lang.reflect.Field.getAnnotatedType(Field.java:1170)
        at org.hibernate.validator.internal.metadata.provider.TypeAnnotationAwareMetaDataProvider.findTypeAnnotationConstraintsForMember(TypeAnnotationAwareMetaDataProvider.java:65)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findPropertyMetaData(AnnotationMetaDataProvider.java:246)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getFieldMetaData(AnnotationMetaDataProvider.java:229)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.retrieveBeanConfiguration(AnnotationMetaDataProvider.java:137)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfiguration(AnnotationMetaDataProvider.java:125)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfigurationForHierarchy(AnnotationMetaDataProvider.java:108)
        at org.hibernate.validator.internal.metadata.BeanMetaDataManager.createBeanMetaData(BeanMetaDataManager.java:203)
        at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getOrCreateBeanMetaData(BeanMetaDataManager.java:231)
        at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getBeanMetaData(BeanMetaDataManager.java:178)
        at org.hibernate.validator.internal.engine.ValidatorImpl.buildNewLocalExecutionContext(ValidatorImpl.java:771)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraint(ValidatorImpl.java:754)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraints(ValidatorImpl.java:681)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:420)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:208)
        at io.dropwizard.configuration.BaseConfigurationFactory.validate(BaseConfigurationFactory.java:236)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:128)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
```

**Comment by TheRealMarnes** [comment] 2019-07-04 22:10
I get the feeling this NPE is not for the jdbi team to investigate and fix, but for the dropwizard team, whose dropwizard-jdbi3 library you're using, or possibly hibernate-validator. There's no jdbi class in the stacktrace so it's farfetched to pin this on jdbi, unless we're mistakenly returning a null value from some piece of API that should never return null.

I would check with dropwizard first. Maybe one of us will try to set up the project you described to reproduce the error, but since nothing so far indicates a code issue in jdbi itself, I think chances are slim/priority is low.

@qualidafial may have a different perspective to offer?

**Comment by qualidafial** [comment] 2019-07-05 01:25
I concur--based on the stack trace this doesn't appear to be caused by Jdbi. I suggest debugging the exception to find out what it's trying to do with that annotation that fails.

**Comment by qualidafial** [comment] 2019-07-05 01:28
Closing as this issue appears not to be related to the Jdbi project. If you find further information that leads you back here, feel free to reopen.

**Closed by qualidafial** 2019-07-05 01:28 UTC
